export interface RetailData {
    Id: number,
    HSHD_NUM: number,
    L: string,
    AGE_RANGE: string,
    MARITAL: string,
    INCOME_RANGE: string,
    HOMEOWNER: string,
    HSHD_COMPOSITION: string,
    HH_SIZE: string,
    CHILDREN: string,
    BASKET_NUM: number,
    PURCHASE_: Date,
    PRODUCT_NUM: number,
    SPEND: number,
    UNITS: number,
    STORE_R: string,
    WEEK_NUM: number,
    YEAR: number,
    DEPARTMENT: string,
    COMMODITY: string,
    BRAND_TY: string,
    NATURAL_ORGANIC_FLAG: string
}